# -*- coding: utf-8 -*-
"""Inst_01_Aula_Pratica_02_Estrutura_Cond

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hyzyON-Pvj_c9h8L8Y-f_VaNQEQvcAYo

# Primeiros Passos na Programação

Aqui vamos apresentar todos os tópicos discutidos em sala de aula pelo professor, com uma ou duas células com exemplos práticos da aplicação do comando ou recurso. A seguir a lista de tópicos trabalhados:

* Primeiro programa
* Expressões relacionais
* Expressões lógicas
* Estruturas condicionais
* Estruturas condicionais aninhadas

Para maiores informações segue um pequeno tutorial: [Tutorial de Python](https://docs.python.org/pt-br/3/tutorial/)

# Primeiro programa
"""

print('Olá, Mundo!')

# Definindo variáveis e solicitando entrada do usuário
nome = input("Digite seu nome: ")

# Exibindo os dados do usuário
print("\nInformações do usuário:")
print("Nome:", nome)

# Operações básicas
numero1 = int(input("\nDigite o primeiro número: "))
numero2 = int(input("Digite o segundo número: "))

soma = numero1 + numero2
print(f"\n{numero1} + {numero2} = {soma}")

# Definindo variáveis e solicitando entrada do usuário
nome = input("Digite seu nome: ")
idade = int(input("Digite sua idade: "))
altura = float(input("Digite sua altura em metros (ex: 1.75): "))

# Exibindo os dados do usuário
print("\nInformações do usuário:")
print("Nome:", nome)
print("Idade:", idade)
print("Altura:", altura)

# Operações básicas
numero1 = int(input("\nDigite o primeiro número: "))
numero2 = int(input("Digite o segundo número: "))

# Soma
soma = numero1 + numero2
print(f"\n{numero1} + {numero2} = {soma}")

# Subtração
subtracao = numero1 - numero2
print(f"{numero1} - {numero2} = {subtracao}")

# Multiplicação
multiplicacao = numero1 * numero2
print(f"{numero1} * {numero2} = {multiplicacao}")

# Divisão
if numero2 != 0:
    divisao = numero1 / numero2
    print(f"{numero1} / {numero2} = {divisao:.2f}")
else:
    print("Divisão por zero não é permitida.")

# Exponenciação
exponenciacao = numero1 ** numero2
print(f"{numero1} ^ {numero2} = {exponenciacao}")

# Módulo
modulo = numero1 % numero2
print(f"{numero1} % {numero2} = {modulo}")

"""# Expressões relacionais"""

a = 10
b = 20
print(a == b)

a = 10
b = 20
print(a == b)
print(a != b)
print(a > b)
print(a < b)
print(a >= b)
print(a <= b)

"""# Expressões lógicas"""

x = True
y = False

print(x and y)

x = True
y = False
print(x and y)
print(x or y)
print(not x)

"""# Estruturas condicionais"""

# Sintaxe - estrutura condicional simples
if condição:
    # bloco de código

# Exemplo prático
idade=18
if idade >= 18:
    print("Maior de idade.")

# Sintaxe - estrutura condicional composta
if condição:
    # bloco de código se condição for verdadeira
else:
    # bloco de código se condição for falsa

# Exemplo prático
nota = 75
if nota >= 60:
    print("Aprovado")
else:
    print("Reprovado")

# Sintaxe - Estrutura condicional if-elif-else
if condição1:
    # bloco de código se condição1 for verdadeira
elif condição2:
    # bloco de código se condição2 for verdadeira
else:
    # bloco de código se todas as condições anteriores forem falsas

# Exemplo prático
nota = 85
if nota >= 90:
    print("Excelente")
elif nota >= 70:
    print("Bom")
else:
    print("Precisa melhorar")

"""# Estruturas condicionais aninhadas"""

# Estrutura condicional aninhada
# Exemplo prático
idade = 25

if idade < 18:
    print("Menor de idade")
else:
    if idade < 65:
        print("Adulto")
    else:
        print("Idoso")

# Estrutura condicional aninhada - if-elif-else
# Exemplo prático
idade = 25
ocupacao = "estudante"

if idade < 18:
    print("Menor de idade")
    if ocupacao == "estudante":
        print("Estudante menor de idade")
elif idade < 65:
    print("Adulto")
    if ocupacao == "trabalhador":
        print("Adulto trabalhador")
    else:
        print("Adulto não trabalhador")
else:
    print("Idoso")