# -*- coding: utf-8 -*-
"""Inst_01_Aula_Pratica_01_Primeiros_Passos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HUUX83Tj8nK-fX609Y3GTovU3Q7x26Bv

# Primeiros Passos na Programação

Aqui vamos apresentar todos os tópicos discutidos em sala de aula pelo professor, com uma ou duas células com exemplos práticos da aplicação do comando ou recurso. A seguir a lista de tópicos trabalhados:

* Instalando e usando o interpretador
* Entrada de dados
* Saída de dados
* Tipos de dados
* Identificadores e variáveis
* Operadores aritméticos e expressões


Para maiores informações segue um pequeno tutorial: [Tutorial de Python](https://docs.python.org/pt-br/3/tutorial/)

# Executando com o interpretador

* Shift + Enter
* Ctrl + Enter
"""

# Executando um comando
print('Olá Mundo')

# Executando um conjunto de comandos
valor=6
for i in range(1,11):
  print(i,' * ',valor,'=',i*valor)

# Executando com erro de syntaxe
valor=6
for i in range(1,11,2,3):
  print(i,' * ',valor,'=',i*valor)

"""# Entrada de dados"""

input('Informe um valor.: ')

nome = input('Informe um nome.: ')

"""# Saída de dados"""

valor = 200
print('Informe um valor')
print(valor)
print('O valor informado foi', valor)

valor = 200
print('O valor informado foi', valor)

valor = 200
print('O valor informado foi\n', valor)

"""# Tipos de dados"""

A = 23
B = 'Universidade'
C = 2.5
D = True

print(A)
print(B)
print(C)
print(D)

print(type(A))
print(type(B))
print(type(C))
print(type(D))

"""# Identificadores e variáveis"""

# Atribuição de variáveis
nome = "João"
idade = 25
altura = 1.75
estudante = True

# Imprimindo os valores
print(nome)
print(idade)
print(altura)
print(estudante)

nome_completo = input('Informe o seu nome completo: ')
endereco_de_atendimento = input('Qual o endereço de entrega')

"""
# Operadores aritméticos e expressões"""

# Valores
valor1 = 10
valor2 = 20

# Variáveis
x = valor1
y = valor2

# Operadores
soma = x + y
subtracao = x - y
produto = x * y
divisao = y / x
modulo = y % x

# Expressão completa
# Combinação de valores, variáveis e operadores
expressao = (soma * produto) / (divisao + modulo)

# Imprimindo os resultados
print("Valor de x:", x)
print("Valor de y:", y)
print("Soma:", soma)
print("Produto:", produto)
print("Divisão:", divisao)
print("Módulo:", modulo)
print("Resultado da expressão:", expressao)

print(20+32)
print(20-12)
print(20*32)
print(20/2)
print(20**2)

X = 7
Y = 6
Z = X + Y
print(Z)

# Os parênteses
print(2 * (3 - 1))
print(2 * 3 - 1)

# Exponenciação
print(2 ** 1 + 1)
print(3 * 1 ** 3)

# Multiplicação e Divisão
# Adição e subtração
print(2 * 3 - 1)
print(6 + 4 / 2)